import logging

def setup_logger(log_file_name):
    FORMATTER = logging.Formatter("%(asctime)s:%(funcName)s:%(levelname)s\n%(message)s")
    # console_logger = logging.StreamHandler(sys.stdout)
    file_logger = logging.FileHandler(log_file_name)
    file_logger.setFormatter(FORMATTER)

    logger = logging.getLogger(log_file_name)
    logger.setLevel(logging.DEBUG)
    logger.addHandler(file_logger)
    logger.propagate = False
    return logger

country_codes = {
  'AFGHANISTAN': 'AF',
  'ALBANIA': 'AL',
  'ALGERIA': 'DZ',
  'AMERICAN SAMOA': 'AS',
  'ANDORRA': 'AD',
  'ANGOLA': 'AO',
  'ANGUILLA': 'AI',
  'ANTARCTICA': 'AQ',
  'ANTIGUA AND BARBUDA': 'AG',
  'ARGENTINA': 'AR',
  'ARMENIA': 'AM',
  'ARUBA': 'AW',
  'AUSTRALIA': 'AU',
  'AUSTRIA': 'AT',
  'AZERBAIJAN': 'AZ',
  'BAHAMAS': 'BS',
  'BAHRAIN': 'BH',
  'BANGLADESH': 'BD',
  'BARBADOS': 'BB',
  'BELARUS': 'BY',
  'BELGIUM': 'BE',
  'BELIZE': 'BZ',
  'BENIN': 'BJ',
  'BERMUDA': 'BM',
  'BHUTAN': 'BT',
  'BOLIVIA': 'BO',
  'BONAIRE SINT EUSTATIUS AND SABA': 'BQ',
  'BOSNIA AND HERZEGOVINA': 'BA',
  'BOTSWANA': 'BW',
  'BOUVET ISLAND': 'BV',
  'BRAZIL': 'BR',
  'BRITISH INDIAN OCEAN TERRITORY': 'IO',
  'BRUNEI DARUSSALAM': 'BN',
  'BRUNEI': 'BN',
  'BULGARIA': 'BG',
  'BURKINA FASO': 'BF',
  'BURUNDI': 'BI',
  'CAMBODIA': 'KH',
  'CAMEROON': 'CM',
  'CANADA': 'CA',
  'CAPE VERDE': 'CV',
  'CAYMAN ISLANDS': 'KY',
  'CENTRAL AFRICAN REPUBLIC': 'CF',
  'CHAD': 'TD',
  'CHILE': 'CL',
  'CHINA': 'CN',
  'CHRISTMAS ISLAND': 'CX',
  'COCOS (KEELING) ISLANDS': 'CC',
  'COLOMBIA': 'CO',
  'COMOROS': 'KM',
  'CONGO': 'CG',
  'DEMOCRATIC REPUBLIC OF CONGO': 'CD',
  'COOK ISLANDS': 'CK',
  'COSTA RICA': 'CR',
  "CÃ”TE D'IVOIRE": 'CI',
  "COTE D'IVOIRE": 'CI',
  'CROATIA': 'HR',
  'CUBA': 'CU',
  'CURACAO': 'CW',
  'CYPRUS': 'CY',
  'CZECH REPUBLIC': 'CZ',
  'DENMARK': 'DK',
  'DJIBOUTI': 'DJ',
  'DOMINICA': 'DM',
  'DOMINICAN REPUBLIC': 'DO',
  'ECUADOR': 'EC',
  'EGYPT': 'EG',
  'EL SALVADOR': 'SV',
  'EQUATORIAL GUINEA': 'GQ',
  'ERITREA': 'ER',
  'ESTONIA': 'EE',
  'ETHIOPIA': 'ET',
  'FALKLAND ISLANDS': 'FK',
  'FALKLAND ISLANDS (MALVINAS)': 'FK',
  'FAEROE ISLANDS': 'FO',
  'FAROE ISLANDS': 'FO',
  'FIJI': 'FJ',
  'FINLAND': 'FI',
  'FRANCE': 'FR',
  'FRENCH GUIANA': 'GF',
  'FRENCH POLYNESIA': 'PF',
  'FRENCH SOUTHERN TERRITORIES': 'TF',
  'GABON': 'GA',
  'GAMBIA': 'GM',
  'GEORGIA': 'GE',
  'GERMANY': 'DE',
  'GHANA': 'GH',
  'GIBRALTAR': 'GI',
  'GREECE': 'GR',
  'GREENLAND': 'GL',
  'GRENADA': 'GD',
  'GUADELOUPE': 'GP',
  'GUAM': 'GU',
  'GUATEMALA': 'GT',
  'GUINEA': 'GN',
  'GUINEA-BISSAU': 'GW',
  'GUYANA': 'GY',
  'GUERNSEY': 'GG',
  'HAITI': 'HT',
  'HEARD ISLAND AND MCDONALD ISLANDS': 'HM',
  'HONDURAS': 'HN',
  'HONG KONG': 'HK',
  'HUNGARY': 'HU',
  'ICELAND': 'IS',
  'INDIA': 'IN',
  'INDONESIA': 'ID',
  'IRAN': 'IR',
  'IRAN, ISLAMIC REPUBLIC OF': 'IR',
  'IRAQ': 'IQ',
  'IRELAND': 'IE',
  'ISLE OF MAN': 'IM',
  'ISRAEL': 'IL',
  'ITALY': 'IT',
  'JAMAICA': 'JM',
  'JAPAN': 'JP',
  'JERSEY': 'JE',
  'JORDAN': 'JO',
  'KAZAKHSTAN': 'KZ',
  'KENYA': 'KE',
  'KIRIBATI': 'KI',
  "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF": 'KP',
  'KOREA, REPUBLIC OF': 'KR',
  'KOSOVO': 'XK',
  'KUWAIT': 'KW',
  'KYRGYZSTAN': 'KG',
  "LAOS": 'LA',
  "LAO PEOPLE'S DEMOCRATIC REPUBLIC": 'LA',
  'LATVIA': 'LV',
  'LEBANON': 'LB',
  'LESOTHO': 'LS',
  'LIBERIA': 'LR',
  'LIBYAN ARAB JAMAHIRIYA': 'LY',
  'LIBYA': 'LY',
  'LIECHTENSTEIN': 'LI',
  'LITHUANIA': 'LT',
  'LUXEMBOURG': 'LU',
  'MACAO': 'MO',
  'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF': 'MK',
  'MACEDONIA': 'MK',
  'MADAGASCAR': 'MG',
  'MALAWI': 'MW',
  'MALAYSIA': 'MY',
  'MALDIVES': 'MV',
  'MALI': 'ML',
  'MALTA': 'MT',
  'MARSHALL ISLANDS': 'MH',
  'MARTINIQUE': 'MQ',
  'MAURITANIA': 'MR',
  'MAURITIUS': 'MU',
  'MAYOTTE': 'YT',
  'MEXICO': 'MX',
  'MICRONESIA, FEDERATED STATES OF': 'FM',
  'MOLDOVA': 'MD',
  'MOLDOVA, REPUBLIC OF': 'MD',
  'MONACO': 'MC',
  'MONGOLIA': 'MN',
  'MONTSERRAT': 'MS',
  'MOROCCO': 'MA',
  'MOZAMBIQUE': 'MZ',
  'MYANMAR': 'MM',
  'NAMIBIA': 'NA',
  'NAURU': 'NR',
  'NEPAL': 'NP',
  'NETHERLANDS': 'NL',
  'NETHERLANDS ANTILLES': 'AN',
  'NEW CALEDONIA': 'NC',
  'NEW ZEALAND': 'NZ',
  'NICARAGUA': 'NI',
  'NIGER': 'NE',
  'NIGERIA': 'NG',
  'NIUE': 'NU',
  'NORFOLK ISLAND': 'NF',
  'NORTHERN MARIANA ISLANDS': 'MP',
  'NORWAY': 'NO',
  'OMAN': 'OM',
  'PAKISTAN': 'PK',
  'PALAU': 'PW',
  'PALESTINE': 'PS',
  'PANAMA': 'PA',
  'PAPUA NEW GUINEA': 'PG',
  'PARAGUAY': 'PY',
  'PERU': 'PE',
  'PHILIPPINES': 'PH',
  'PITCAIRN': 'PN',
  'POLAND': 'PL',
  'PORTUGAL': 'PT',
  'PUERTO RICO': 'PR',
  'QATAR': 'QA',
  'RÃ‰UNION': 'RE',
  'ROMANIA': 'RO',
  'RUSSIA': 'RU',
  'RUSSIAN FEDERATION': 'RU',
  'RWANDA': 'RW',
  'SAINT BARTHLEMY': 'SH',
  'SAINT HELENA': 'SH',
  'SAINT KITTS AND NEVIS': 'KN',
  'SAINT LUCIA': 'LC',
  'SAINT PIERRE AND MIQUELON': 'PM',
  'SAINT VINCENT AND THE GRENADINES': 'VC',
  'SAMOA': 'WS',
  'SAN MARINO': 'SM',
  'SAO TOME AND PRINCIPE': 'ST',
  'SAUDI ARABIA': 'SA',
  'SENEGAL': 'SN',
  'SERBIA': 'RS',
  'MONTENEGRO': 'ME',
  'SEYCHELLES': 'SC',
  'SIERRA LEONE': 'SL',
  'SINT MAARTEN (DUTCH PART)': 'SX',
  'SINGAPORE': 'SG',
  'SLOVAKIA': 'SK',
  'SLOVENIA': 'SI',
  'SOLOMON ISLANDS': 'SB',
  'SOMALIA': 'SO',
  'SOUTH AFRICA': 'ZA',
  'SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS': 'GS',
  'SPAIN': 'ES',
  'SRI LANKA': 'LK',
  'SUDAN': 'SD',
  'SOUTH KOREA': 'KR',
  'SOUTH SUDAN': 'SS',
  'SURINAME': 'SR',
  'SVALBARD AND JAN MAYEN': 'SJ',
  'SWAZILAND': 'SZ',
  'SWEDEN': 'SE',
  'SWITZERLAND': 'CH',
  'SYRIA': 'SY',
  'SYRIAN ARAB REPUBLIC': 'SY',
  'TAIWAN': 'TW',
  'TAIWAN, PROVINCE OF CHINA': 'TW',
  'TAJIKISTAN': 'TJ',
  'TANZANIA': 'TZ',
  'THAILAND': 'TH',
  'TIMOR': 'TL',
  'TOGO': 'TG',
  'TOKELAU': 'TK',
  'TONGA': 'TO',
  'TRINIDAD AND TOBAGO': 'TT',
  'TUNISIA': 'TN',
  'TURKEY': 'TR',
  'TURKMENISTAN': 'TM',
  'TURKS AND CAICOS ISLANDS': 'TC',
  'TUVALU': 'TV',
  'UGANDA': 'UG',
  'UKRAINE': 'UA',
  'UNITED ARAB EMIRATES': 'AE',
  'UNITED KINGDOM': 'GB',
  'UNITED STATES': 'US',
  'UNITED STATES MINOR OUTLYING ISLANDS': 'UM',
  'URUGUAY': 'UY',
  'UZBEKISTAN': 'UZ',
  'VANUATU': 'VU',
  'VIETNAM': 'VN',
  'VIET NAM': 'VN',
  'VIRGIN ISLANDS, BRITISH': 'VG',
  'BRITISH VIRGIN ISLANDS': 'VG',
  'VATICAN': 'VA',
  'VENEZUELA': 'VE',
  'VIRGIN ISLANDS, U.S.': 'VI',
  'UNITED STATES VIRGIN ISLANDS': 'VI',
  'WALLIS AND FUTUNA': 'WF',
  'WESTERN SAHARA': 'EH',
  'YEMEN': 'YE',
  'ZAMBIA': 'ZM',
  'ZIMBABWE': 'ZW',
}
